name: snapshot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  image_picker: ^1.0.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  photo_view: ^0.15.0
  reorderables: ^0.6.0
  http: ^1.2.1
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.0
  uuid: ^4.1.0
  pdf: ^3.10.4
  printing: ^5.12.0
  fl_chart: ^0.64.0
  webview_flutter: ^4.4.2
  confetti: ^0.7.0
  firebase_dynamic_links: ^6.1.9
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  csv: ^5.0.2
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_placeholder.png