name: snapspot_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  image_picker: ^1.0.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_user.png