// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9YWrJBRQUNR8dF5jI31ycCwVLnbZtOo',
    appId: '1:466117666534:web:025cf44bd83f4ba72c7d27',
    messagingSenderId: '466117666534',
    projectId: 'capstone-2d2ce',
    authDomain: 'capstone-2d2ce.firebaseapp.com',
    storageBucket: 'capstone-2d2ce.firebasestorage.app',
    measurementId: 'G-EGPCT2YPFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhW1gjuY14-ARXTGXOnOWMIScsJdVzE8',
    appId: '1:466117666534:android:c6b2c1a7411c2a272c7d27',
    messagingSenderId: '466117666534',
    projectId: 'capstone-2d2ce',
    storageBucket: 'capstone-2d2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGKu7MxgzkJNmRKogQVXOu5fjROSb-IHY',
    appId: '1:466117666534:ios:46010c42014fd5d12c7d27',
    messagingSenderId: '466117666534',
    projectId: 'capstone-2d2ce',
    storageBucket: 'capstone-2d2ce.firebasestorage.app',
    iosBundleId: 'com.example.snapshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGKu7MxgzkJNmRKogQVXOu5fjROSb-IHY',
    appId: '1:466117666534:ios:46010c42014fd5d12c7d27',
    messagingSenderId: '466117666534',
    projectId: 'capstone-2d2ce',
    storageBucket: 'capstone-2d2ce.firebasestorage.app',
    iosBundleId: 'com.example.snapshot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB9YWrJBRQUNR8dF5jI31ycCwVLnbZtOo',
    appId: '1:466117666534:web:e456d44ead1157ba2c7d27',
    messagingSenderId: '466117666534',
    projectId: 'capstone-2d2ce',
    authDomain: 'capstone-2d2ce.firebaseapp.com',
    storageBucket: 'capstone-2d2ce.firebasestorage.app',
    measurementId: 'G-K8E44H7T5G',
  );

}